- uses: actions/checkout@v4

- uses: webfactory/ssh-agent@v0.9.0
  with:
    ssh-private-key: ${{ secrets.SSH_KEY }}

- name: Add known_hosts
  run: |
    mkdir -p ~/.ssh
    ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

- name: Test SSH
  run: |
    ssh -o IdentitiesOnly=yes ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo connected"

- name: Deploy
  run: |
    rsync -avz --delete \
      -e "ssh -o IdentitiesOnly=yes" \
      --exclude ".git" \
      --exclude ".github" \
      ./ \
      ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/portfolio.geissel.io/html/